# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = [
    { :name => :nfssrv, :box_name => "centos/7", :ip_addr => '192.168.11.102' },
    { :name => :nfsclient, :box_name => "centos/7", :ip_addr => '192.168.11.101'}
  ]

Vagrant.configure("2") do |config|
    # I have this plugin and do not want it here. You may not have it anyway.
    if Vagrant.has_plugin?("vagrant-vbguest")
      config.vbguest.auto_update = false
    end
    
    config.vm.box_version = "1804.02"
    MACHINES.each do |boxconfig|
    
        config.vm.define boxconfig[:name] do |box|
            playbook = boxconfig[:name].to_s+".yml"
            box.vm.synced_folder ".", "/vagrant", disabled: true
            box.vm.box = boxconfig[:box_name]
            box.vm.hostname = boxconfig[:name].to_s
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "256"]
            end
          
            box.vm.provision "ansible" do |ansible|
              ansible.playbook = playbook
              ansible.verbose = "v"
            end
        end
    end
end
