# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

# MACHINES = {
#  :nfs_srv => {
#        :box_name => "centos/7",
#        :ip_addr => '192.168.11.102'
#   },
#   :nfs_client => {
#         :box_name => "centos/7",
#         :ip_addr => '192.168.11.101'
#   }
# }
MACHINES = [
    { :name => :nfs_srv, :box_name => "centos/7", :ip_addr => '192.168.11.102' },
    { :name => :nfs_client, :box_name => "centos/7", :ip_addr => '192.168.11.101'}
  ]

Vagrant.configure("2") do |config|

    config.vm.box_version = "1804.02"
    MACHINES.each do |boxconfig|
    
        config.vm.define boxconfig[:name] do |box|
            box.vm.synced_folder ".", "/vagrant", disabled: true
            box.vm.box = boxconfig[:name]
            box.vm.hostname = boxname.to_s
	    
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "256"]
            end
          
            box.vm.provision "ansible" do |ansible|
              ansible.playbook = boxсonfig{:name]".yml"
            end
        end
    end
end
