- name: Install NGINX from Epel 
  hosts: nginx
  become: true

  vars:
    nginx_listen_port: 8081
    ansible_managed: created with ansible, do not touch!
  tasks:
    - name: Install EPEL repo with yum
      yum_repository:
        name: epel-release
        description: Centos 7 Epel Repo
        baseurl: https://dl.fedoraproject.org/pub/epel/$releasever/$basearch
        mirrorlist: mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
        state: present
      tags:
        - epel-package
        - packages

    - name: NGINX | Install NGINX package from EPEL Repo
      yum:
        name: nginx
        state: latest
      notify:
         - restart_nginx
      tags:
        - nginx-package
        - packages

    - name: NGINX | Create NGINX config file from template
      template:
        src: ../templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - reload_nginx
      tags: 
        - nginx-configuration 

  handlers:
    - name: restart_nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
    
    - name: reload_nginx
      systemd:
        name: nginx
        state: reloaded
