- name: Install EPEL repo
  hosts: nginx
  become: true

  vars:
    nginx_listen_port: 8080

  tasks:
    - name: Install EPEL repo with yum
      yum:
        name: epel-release
        state: present
      notify:
         - restart nginx
      tags:
        - epel-package
        - packages

    - name: NGINX | Install NGINX package from EPEL Repo
      yum:
        name: nginx
        state: latest
      notify:
        - reload nginx
      tags:
        - nginx-package
        - packages

    - name: NGINX | Create NGINX config file from template
      template:
        src: ../templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      tags: 
        - nginx-configuration 

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
    
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded
