# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Указываем имя бокса и хостнейм виртуалки
  config.vm.box = "centos/7"
  config.vm.hostname = "disk2raid"

 config.vm.provider "virtualbox" do |vb|
  # Включаем консоль Virtualbox на загрузке - понадобится, чтобы загрузиться с нового диска
  # Указываем имя виртуалки для удобства
  vb.gui = true
  vb.name = "disk2raid"
  
   vb.memory = "1024"
   
   # Описываем процедуру добавления диска
   second_disk = "./disk2.vmdk"
   # Создаем второй виртуальный диск такого же объема, как в базовом боксе, если не был создан ранее
   unless File.exist?(second_disk)
     vb.customize ['createhd', '--filename', second_disk, '--size', 40960 ]
   end
   # Подсоединяем диск к уже существующему контроллеру, т.к. не хочется плодить сущности.
   # В нашем случае, в базовом боксе уже есть двухпортовый контроллер IDE
   # Имя можно узнать командами 'VBoxManage showvminfo <имя_виртуалки>'
   # или 'VBoxManage list vms -l'
   vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', second_disk]

 end
  # Ставим mdadm для работы с рейдом
  config.vm.provision "shell", inline: <<-SHELL
      yum install -y mdadm
  SHELL
end
