    - name: Install EPEL repo with yum_repository
      yum_repository:
        name: epel-release
        description: Centos 7 Epel Repo
        baseurl: https://dl.fedoraproject.org/pub/epel/$releasever/$basearch
        mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
        state: present
        enabled: yes
      tags:
        - epel-package
        - packages

    - name: NGINX | Install NGINX package from EPEL Repo
      yum:
        name: nginx
        state: latest
        disable_gpg_check: yes
      notify:
        - restart_nginx
      tags:
        - nginx-package
        - packages

    - name: NGINX | Create NGINX config file from template
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - reload_nginx
      tags:
        - nginx-configuration

